/**
 * SPM Voting Script
 * 
 * Run a complete voting round on testnet:
 * 1. Get current nullifier root
 * 2. Generate ZK proof
 * 3. Submit vote to contract
 * 
 * Usage: node vote_spm.js <vote> [--network testnet|futurenet]
 *   vote: 0 (no) or 1 (yes)
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Configuration
const CONTRACT_ID = 'CCQ3T4VKYXBGJQ3BXPUCKOW4CDFQ5YR4UY4N54QY4EJOWC2NEYIJJZQI';
const NETWORK = process.argv.includes('--futurenet') ? 'futurenet' : 'testnet';
const KEY_ALIAS = 'spm-deployer';

// Colors for output
const colors = {
    reset: '\x1b[0m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    blue: '\x1b[34m',
    red: '\x1b[31m'
};

function log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
}

function logSection(title) {
    console.log(`\n${'='.repeat(60)}`);
    log(title, 'blue');
    console.log('='.repeat(60));
}

// Get current nullifier root from contract
function getNullifierRoot() {
    logSection('1. Getting Current Nullifier Root');
    
    try {
        const result = execSync(
            `stellar contract invoke --id ${CONTRACT_ID} --source-account ${KEY_ALIAS} --network ${NETWORK} -- get_nullifier_root`,
            { encoding: 'utf8' }
        );
        log('Current nullifier root: ' + result.trim(), 'green');
        return result.trim();
    } catch (e) {
        log('Error getting nullifier root: ' + e.message, 'red');
        // Return empty root for initial vote
        return '0';
    }
}

// Get current market status
function getStatus() {
    logSection('2. Getting Market Status');
    
    try {
        const result = execSync(
            `stellar contract invoke --id ${CONTRACT_ID} --source-account ${KEY_ALIAS} --network ${NETWORK} -- get_status`,
            { encoding: 'utf8' }
        );
        const statusCode = parseInt(result.trim());
        const statuses = ['Open', 'Closed', 'Resolved'];
        log('Market status: ' + statuses[statusCode] + ' (' + statusCode + ')', 'green');
        return statusCode;
    } catch (e) {
        log('Error getting status: ' + e.message, 'red');
        return -1;
    }
}

// Get total votes
function getTotalVotes() {
    logSection('3. Getting Vote Count');
    
    try {
        const result = execSync(
            `stellar contract invoke --id ${CONTRACT_ID} --source-account ${KEY_ALIAS} --network ${NETWORK} -- get_total_votes`,
            { encoding: 'utf8' }
        );
        log('Total votes: ' + result.trim(), 'green');
        return parseInt(result.trim());
    } catch (e) {
        log('Error getting votes: ' + e.message, 'red');
        return 0;
    }
}

// Generate ZK proof
function generateProof(vote) {
    logSection('4. Generating ZK Proof');
    
    try {
        // Generate random secret
        const secret = Math.floor(Math.random() * Number.MAX_SAFE_INTEGER).toString();
        log('Voter secret (save this!): ' + secret, 'yellow');
        
        // Run the proof generator
        const proofPath = path.join(__dirname, '../circuits/testdata/proof.json');
        
        // Create proof data (simplified for demo)
        // In production, this would call the circom WASM prover
        const { execSync: exec } = require('child_process');
        
        // Generate mock proof with snarkjs-compatible format
        const proofData = {
            nullifier: '0x' + Array.from({length: 64}, () => 
                Math.floor(Math.random() * 16).toString(16)).join(''),
            vote_commitment: '0x' + Array.from({length: 64}, () => 
                Math.floor(Math.random() * 16).toString(16)).join(''),
            // These are mock proof points - in production, generated by circom
            proof_a: [
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join(''),
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join('')
            ],
            proof_b: [[
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join(''),
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join('')
            ], [
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join(''),
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join('')
            ]],
            proof_c: [
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join(''),
                '0x' + Array.from({length: 64}, () => 
                    Math.floor(Math.random() * 16).toString(16)).join('')
            ]
        };
        
        fs.writeFileSync(proofPath, JSON.stringify(proofData, null, 2));
        log('Proof data saved to: ' + proofPath, 'green');
        
        return proofData;
    } catch (e) {
        log('Error generating proof: ' + e.message, 'red');
        throw e;
    }
}

// Submit vote
function submitVote(vote, proofData, nullifierRoot) {
    logSection('5. Submitting Vote');
    
    const voteInt = parseInt(vote);
    log('Vote: ' + voteInt + ' (' + (voteInt === 1 ? 'YES' : 'NO') + ')', 'green');
    
    try {
        // Build the invoke command
        const cmd = [
            'stellar contract invoke',
            `--id ${CONTRACT_ID}`,
            `--source-account ${KEY_ALIAS}`,
            `--network ${NETWORK}`,
            '--',
            'submit_vote',
            `--voter GDRXE2BQUC3AZNPVFSCEZ76NJ3TSL9NSESYFPJKGNWQYLHOQVTVEJ3E2`,
            `--nullifier ${proofData.nullifier}`,
            `--vote_commitment ${proofData.vote_commitment}`,
            `--proof_a '${JSON.stringify(proofData.proof_a)}'`,
            `--proof_b '${JSON.stringify(proofData.proof_b)}'`,
            `--proof_c '${JSON.stringify(proofData.proof_c)}'`
        ].join(' ');
        
        log('Command: ' + cmd, 'yellow');
        
        const result = execSync(cmd, { encoding: 'utf8' });
        log('Vote submitted successfully!', 'green');
        log('Result: ' + result.trim());
        
        return result;
    } catch (e) {
        log('Error submitting vote: ' + e.message, 'red');
        if (e.stderr) log('stderr: ' + e.stderr.toString(), 'red');
        throw e;
    }
}

// Close market
function closeMarket() {
    logSection('Closing Market');
    
    try {
        const result = execSync(
            `stellar contract invoke --id ${CONTRACT_ID} --source-account ${KEY_ALIAS} --network ${NETWORK} -- --send=yes close_market`,
            { encoding: 'utf8' }
        );
        log('Market closed!', 'green');
        log('Result: ' + result.trim());
        return result;
    } catch (e) {
        log('Error closing market: ' + e.message, 'red');
        throw e;
    }
}

// Resolve market
function resolveMarket(votesYes, votesNo, minorityThreshold) {
    logSection('Resolving Market');
    
    log(`Votes: YES=${votesYes}, NO=${votesNo}, Threshold=${minorityThreshold}%`);
    
    try {
        const result = execSync(
            `stellar contract invoke --id ${CONTRACT_ID} --source-account ${KEY_ALIAS} --network ${NETWORK} -- --send=yes resolve --votes_yes ${votesYes} --votes_no ${votesNo} --minority_threshold ${minorityThreshold}`,
            { encoding: 'utf8' }
        );
        log('Market resolved!', 'green');
        log('Result: ' + result.trim());
        return result;
    } catch (e) {
        log('Error resolving market: ' + e.message, 'red');
        throw e;
    }
}

// Main execution
async function main() {
    const vote = process.argv[2] || '1';
    const autoResolve = process.argv.includes('--resolve');
    
    log('SPM Voting Round', 'blue');
    log('Contract: ' + CONTRACT_ID);
    log('Network: ' + NETWORK);
    log('Time: ' + new Date().toISOString());
    
    // Step 1: Check market status
    const status = getStatus();
    
    if (status === 2) {
        log('Market is already resolved!', 'yellow');
        const result = getStatus();
        return;
    }
    
    // Step 2: Get current state
    const nullifierRoot = getNullifierRoot();
    const totalVotes = getTotalVotes();
    
    // Step 3: Generate proof
    const proofData = generateProof(vote);
    
    // Step 4: Submit vote
    const txResult = submitVote(vote, proofData, nullifierRoot);
    
    // Extract transaction hash
    const txMatch = txResult.match(/tx\/([a-f0-9]+)/);
    const txHash = txMatch ? txMatch[1] : null;
    
    // Step 5: Verify vote was recorded
    logSection('6. Verifying Vote');
    const newTotal = getTotalVotes();
    log('Vote recorded! Total votes now: ' + newTotal, 'green');
    
    // Save transaction info
    const voteRecord = {
        contractId: CONTRACT_ID,
        network: NETWORK,
        vote: parseInt(vote),
        txHash: txHash,
        timestamp: new Date().toISOString(),
        proofData: proofData,
        explorer: `https://stellar.expert/explorer/${NETWORK}/tx/${txHash}`
    };
    
    const recordPath = path.join(__dirname, '../docs/voting_round_' + Date.now() + '.json');
    fs.writeFileSync(recordPath, JSON.stringify(voteRecord, null, 2));
    log('Vote record saved to: ' + recordPath, 'green');
    
    // Auto resolve if requested
    if (autoResolve && newTotal >= 3) {
        logSection('Auto-Resolving Market');
        
        // Get current votes (simplified - would need to track actual votes)
        const votesYes = 2;
        const votesNo = newTotal - 2;
        
        closeMarket();
        resolveMarket(votesYes, votesNo, 30);
    }
    
    logSection('Voting Round Complete!');
    log('Transaction: ' + (txHash ? `https://stellar.expert/explorer/${NETWORK}/tx/${txHash}` : 'pending'), 'green');
    
    return voteRecord;
}

main().catch(e => {
    log('Fatal error: ' + e.message, 'red');
    process.exit(1);
});
